import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import Link from 'next/link'
import "./globals.css";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Link href="/carrito">carrito</Link>
        <br />
        <Link href="/productos">productos</Link>
        <br />
        <Link href="/productos/detalleproducto">detalleproducto</Link>
        {children}
      </body>
    </html>
  );
}
